id: exposed-git-config

info:
  name: Exposed Git Config
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    Git configuration files may contain sensitive information such as repository details, credentials, and configuration settings.
    Exposed .git/config files can lead to information disclosure and potentially unauthorized access.
  tags: git,exposure,config,devops

http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[core]"
        part: body

      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<!doctype html')"